[cost_monitoring_targets]
i-06a9b5df345d47eaa
i-0a0f8fb479bd30b5d
i-0d53ba43b64510164
i-0dc3c13df82448939
i-0c30cae12f60d69d1
i-074a73c3cf9656989

[cost_monitoring_targets:vars]
# 아마존 공식 플러그인 사용
ansible_connection=amazon.aws.aws_ssm
# 리전 설정 (us-west-2 확인됨)
ansible_aws_ssm_region=us-west-2
# 파이썬 경로
ansible_python_interpreter=/usr/bin/python3
